CREATE ROLE caf
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE dev LOGIN
  ENCRYPTED PASSWORD 'md5648836bf02c3eae180dbdd93d5097667'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT caf TO dev;
